spring:
   application:
      name: service-gallery
   profiles:
      active: development


---
#
# development configuration
#
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777


---
#
# production configuration
#
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.0.57:7777